title: Michael Pavkovic's Blog
author: Michael Pavkovic
email: your-email@domain.com
description: >
  Welcome to my blog! Here, you will find all sorts of
  content ranging from Android to computers to robotics. Enjoy!
baseurl: ""
url: "https://michaelminer20.github.io"
twitter_username: michaelminer20
github_username:  michaelminer20
freelancer_username: mpavkovic688
privacy_policy: Privacy Policy

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock

# Google services
google_analytics: UA-92571020-1
